# Generated by Django 4.0.4 on 2022-08-03 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0002_trip_delete_createnewtrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('image', models.ImageField(upload_to='media/')),
                ('bio', models.CharField(max_length=300)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
