# Generated by Django 4.0.4 on 2022-08-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
